# Generated by Django 4.1.7 on 2023-03-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'mi departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
    ]
