# Generated by Django 4.1.7 on 2023-03-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidades',
            old_name='habilidades',
            new_name='habilida',
        ),
    ]
