# Generated by Django 4.1.7 on 2023-04-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_rename_habilidades_habilidades_habilida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='habilida',
            field=models.CharField(max_length=100, verbose_name='Habilidad'),
        ),
    ]
